title: Fouziya Memon
logo: /assets/img/IMG_0113.JPG
description: To pursue a key technical role in an organization where I can utilize my skills, passion, ideas, energy and contribute to achieve vision, mission, and goals of the company. I want to be valuable and important asset to any organization that recognizes my work potential and overall skills to achieve holistic objective of the company to stakeholders and to society. Firm Believer in the phrase “Hard work always leads to success & Success easily comes to those who always take actions.”
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
